service: rest-api-serverless

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  environment: ${file(./env.yml):${self:provider.stage}}

functions:
  createuser:
    handler: api/create.createUser
    events:
      - http:
          path: /create/user
          method: post
          cors: true
  authlogin:
    handler: api/login.login
    events:
      - http:
          path: /login
          method: post
          cors: true
  createpost:
    handler: api/create.createPost
    events:
      - http:
          path: /create/post
          method: post
          cors: true
  createtag:
    handler: api/create.createTag
    events:
      - http:
          path: /create/tag
          method: post
          cors: true
  deleteuser:
    handler: api/delete.deleteUser
    events:
      - http:
          path: /delete/user/{id}
          method: delete
          cors: true
  deletepost:
    handler: api/delete.deletePost
    events:
      - http:
          path: /delete/post/{id}
          method: delete
          cors: true
  deletetag:
    handler: api/delete.deleteTag
    events:
      - http:
          path: /delete/tag/{id}
          method: delete
          cors: true
  listuser:
    handler: api/list.listUser
    events:
      - http:
          path: /list/user
          method: get
          cors: true
  listpost:
    handler: api/list.listPost
    events:
      - http:
          path: /list/post
          method: get
          cors: true
  listtag:
    handler: api/list.listTag
    events:
      - http:
          path: /list/tag
          method: get
          cors: true



plugins:
  - serverless-offline